# Generated by Django 4.2 on 2023-12-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='nationalid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='phonenumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
