# Generated by Django 4.2 on 2023-12-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_remove_ticket_nationalid_remove_ticket_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='phonenumber',
            field=models.CharField(max_length=11),
        ),
    ]
