# Generated by Django 4.2 on 2023-12-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_ticket_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='course.course'),
            preserve_default=False,
        ),
    ]
