# Generated by Django 5.0 on 2023-12-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
